### ISSUE TITLE
Thinner layout (enhancement request)

### ISSUE THREAD

**Issue by stevexyz** [math0ne/keyboard-gherkin#2]
Let's start saying that I LOVE the Gherkin, and I've (unfortunately) really a LOT of keyboard to compare it with!

I have built 2 of them and created a dedicated keymap that is very efficient even for everyday use.

But for me would be even better to have a thinner layout with the promicro placed on the key side and not on the bottom.

Putting this on top of the PCB I think the deeper width  it would make it even more stable. The left space might be used for some optional slider, leds, knobs, displays, etc.

Hope you like the idea. I'm following 40percent.club always hoping to see something like this! :)

**Comment by math0ne** [comment]
I am not the creator, and there is no way to contact the creator that I can find anyways: https://www.40percent.club/
